version: "3"

services:
  jenkins:
    image: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /Users/Guto/Desenvolvimento/Docker/ci/jenkins:/var/jenkins_home

  sonarqube:
    image: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /Users/Guto/Desenvolvimento/Docker/ci/sonarqube/conf:/opt/sonarqube/conf
      - /Users/Guto/Desenvolvimento/Docker/ci/sonarqube/data:/opt/sonarqube/data
      - /Users/Guto/Desenvolvimento/Docker/ci/sonarqube/extensions:/opt/sonarqube/extensions
      - /Users/Guto/Desenvolvimento/Docker/ci/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /Users/Guto/Desenvolvimento/Docker/ci/postgres:/var/lib/postgresql
      - /Users/Guto/Desenvolvimento/Docker/ci/postgres/data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
